version: '3'
services:
  geoserver:
    image: 'geotekne/geoserver:lime-buster-2.20.4'
    hostname: geoserver
    user: root
    environment:
      - STABLE_EXTENSIONS=grib-plugin,netcdf-plugin,netcdf-out-plugin
      - GEOSERVER_DATA_DIR=/var/local/geoserver
      - JAVA_OPTS=-DNETCDF_DATA_DIR=/tmp
    volumes:
      - './data/geoserver/datadir:/var/local/geoserver'
      - './data/geoserver/tmp:/tmp'
    restart: on-failure
    ports:
      - '8080:8080'
    networks:
      - geoserver-net

  wmsclient:
    image: 'nginx:1.21.3-alpine'
    hostname: wmsclient
    volumes:
      - './data/nginx/html:/usr/share/nginx/html'
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - geoserver-net

  weatherdb:
    image: 'kartoza/postgis:12.1'
    hostname: weatherdb
    env_file:
      - ./postgis.env
    volumes:
      - 'pgdata:/var/lib/postgresql'
    ports:
      - "5432:5432"      
    expose:
      - '5432'
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d weather"
    networks:
      - geoserver-net

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=admin@geotekne.com.ar
      - PGADMIN_DEFAULT_PASSWORD=geotekne
    ports:
      - "81:80"
    depends_on:
      - weatherdb
    volumes:
      - './conf/pgadmin/servers.json:/pgadmin4/servers.json'
    restart: always
    networks:
      - geoserver-net

  ncep-weather-worker:
      volumes:
          - ./data/nomads_ncep_noaa:/tmp/datastore
          - ./conf/ncep-weather-worker/config.sh:/scripts/config.sh
      container_name: ncep-weather-worker
      image: 0netx/ncep-weather-worker:1.0.3      
      build:
        context: .
        dockerfile: Dockerfile
      env_file: "worker.env"
  

  # TODO: Add ncep-weather-worker and extended-crontab-ui

volumes: 
    pgdata:
    dbbackups:
    postgis-data:

networks:
  geoserver-net:
    driver: bridge